blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question or discuss an idea
    url: https://t.me/CSPRDevelopers
    about: Ask your questions and discuss your ideas in the CSPR Developers Group

